<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<groupId>fr.alexanj.proto</groupId>
	<artifactId>testapp</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<packaging>pom</packaging>
    <name>${project.artifactId}</name>
    <description>2RO - ABS</description>

	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>4.1.0</version>
	</parent>

    <modules>
        <module>testapp-back</module>
        <module>testapp-front</module>
    </modules>
    
	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<java.version>26</java.version>
        <maven.compiler.source>26</maven.compiler.source>
        <maven.compiler.target>26</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>

        <!-- Node.js version -->
        <node.version>v22.5.0</node.version>   <!-- or latest LTS -->
        <npm.version>10.8.2</npm.version>

        <!-- Angular build output directory -->
        <angular.build.directory>dist/test</angular.build.directory>
	</properties>

</project>
